### ISSUE TITLE
[BUG] SyntaxError: Unexpected token 'export'  编辑器启动之后报错

### ISSUE THREAD

**Issue by lichangwei123** [cweijan/vscode-office#147]
- OS:
- Extension Version:
export const convertMd = async (options) => {
^^^^^^

SyntaxError: Unexpected token 'export'
	at Object.compileFunction (node:vm:352:18)
	at wrapSafe (node:internal/modules/cjs/loader:1038:15)
	at Module._compile (node:internal/modules/cjs/loader:1072:27)
	at Object..js (node:internal/modules/cjs/loader:1169:10)
	at Module.load (node:internal/modules/cjs/loader:988:32)
	at node:internal/modules/cjs/loader:829:12
	at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13331)
	at Function.<anonymous> (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extensionHostProcess.js:40:33)
	at Function.load (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extHostExtensionService.js:17:41)
	at Function.load [as _load] (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/proxyResolver.js:101:37)
	at Module.require (node:internal/modules/cjs/loader:1012:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/Users/liuchongyang/site/vscode/extensions/vscode-office-master/out/service/markdownService.js:38:24)
	at Module._compile (node:internal/modules/cjs/loader:1116:14)
	at Object..js (node:internal/modules/cjs/loader:1169:10)
	at Module.load (node:internal/modules/cjs/loader:988:32)
	at node:internal/modules/cjs/loader:829:12
	at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13331)
	at Function.<anonymous> (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extensionHostProcess.js:40:33)
	at Function.load (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extHostExtensionService.js:17:41)
	at Function.load [as _load] (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/proxyResolver.js:101:37)
	at Module.require (node:internal/modules/cjs/loader:1012:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/Users/liuchongyang/site/vscode/extensions/vscode-office-master/out/provider/officeEditorProvider.js:35:27)
	at Module._compile (node:internal/modules/cjs/loader:1116:14)
	at Object..js (node:internal/modules/cjs/loader:1169:10)
	at Module.load (node:internal/modules/cjs/loader:988:32)
	at node:internal/modules/cjs/loader:829:12
	at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13331)
	at Function.<anonymous> (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extensionHostProcess.js:40:33)
	at Function.load (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extHostExtensionService.js:17:41)
	at Function.load [as _load] (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/proxyResolver.js:101:37)
	at Module.require (node:internal/modules/cjs/loader:1012:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/Users/liuchongyang/site/vscode/extensions/vscode-office-master/out/extension.js:30:32)
	at Module._compile (node:internal/modules/cjs/loader:1116:14)
	at Object..js (node:internal/modules/cjs/loader:1169:10)
	at Module.load (node:internal/modules/cjs/loader:988:32)
	at node:internal/modules/cjs/loader:829:12
	at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13331)
	at Function.<anonymous> (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extensionHostProcess.js:40:33)
	at Function.load (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extHostExtensionService.js:17:41)
	at Function.load [as _load] (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/proxyResolver.js:101:37)
	at Module.require (node:internal/modules/cjs/loader:1012:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.nodeRequire [as __$__nodeRequire] (/Users/liuchongyang/site/vscode/out/vs/loader.js:1071:24)
	at ExtHostExtensionService._loadCommonJSModule (/Users/liuchongyang/site/vscode/out/vs/workbench/api/node/extHostExtensionService.js:87:29)
	at ExtHostExtensionService._doActivateExtension (/Users/liuchongyang/site/vscode/out/vs/workbench/api/common/extHostExtensionService.js:251:22)
	at ExtHostExtensionService._activateExtension (/Users/liuchongyang/site/vscode/out/vs/workbench/api/common/extHostExtensionService.js:221:25)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ActivationOperation._activate (/Users/liuchongyang/site/vscode/out/vs/workbench/api/common/extHostExtensionActivator.js:281:31)
	at async ActivationOperation._waitForDepsThenActivate (/Users/liuchongyang/site/vscode/out/vs/workbench/api/common/extHostExtensionActivator.js:277:13)
	at async ActivationOperation._initialize (/Users/liuchongyan

![image](https://user-images.githubusercontent.com/46671582/199921350-73b7d814-b29b-41d0-aa9a-16db73ac0d07.png)

**Comment by cweijan** [comment]
你的vscode和扩展看起来都不是正常安装的.
