### ISSUE TITLE
[BUG] can not preview csv file with code server

### ISSUE THREAD

**Issue by kebe7jun** [cweijan/vscode-office#361]
- OS: Linux
- Extension Version: 3.3.8

![image](https://github.com/user-attachments/assets/0ddbc874-4d2c-4604-bf5c-d53c77969b0e)

```
Excel-DQ8OtptK.js:147 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'theme')
    at r [as constructor] (Excel-DQ8OtptK.js:147:18393)
    at new r (Excel-DQ8OtptK.js:153:55812)
    at dataCell (Excel-DQ8OtptK.js:155:243440)
    at r.getRowCellInstance (Excel-DQ8OtptK.js:155:106021)
    at t.initTextWrapTemp (Excel-DQ8OtptK.js:155:58097)
    at t.init (Excel-DQ8OtptK.js:155:65998)
    at r.t (Excel-DQ8OtptK.js:155:57635)
    at r [as constructor] (Excel-DQ8OtptK.js:155:76206)
    at new r (Excel-DQ8OtptK.js:155:104606)
    at r.buildFacet (Excel-DQ8OtptK.js:155:242629)
```

**Comment by cweijan** [comment]
Fixed in version 4.0.5.
